# Site settings
author: Ben H.
title: Ben's Web Dev Journal
header-img: img/home-bg.png
email: benhazlerig@msn.com
copyright_name: Ben H.
description: > # this means to ignore newlines until "baseurl:"
  Flatiron Course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BHazlerig

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
